// Writes recipes/INDEX.md: every Recipe by slot, with its numbers and the plans that use it.
// It is how the next Claude finds a Recipe before writing a new one.
//
//   node catalogue.js           check every Recipe and plan, then write recipes/INDEX.md
//   node catalogue.js --check   exit 1 if recipes/INDEX.md is not what would be written
//
// render.js runs the same check and warns when INDEX.md is out of date.

const fs = require('fs');
const path = require('path');
const { SLOTS, loadRecipes, resolvePlan } = require('./lib/recipes');

const ROOT = __dirname;
const INDEX = path.join(ROOT, 'recipes', 'INDEX.md');
const ORDER = ['breakfast', 'snack', 'preworkout', 'lunch', 'dinner'];
const TITLE = { breakfast: 'Breakfast', snack: 'Snack', preworkout: 'Pre-workout', lunch: 'Lunch', dinner: 'Dinner' };

// Returns { text, errors }: the INDEX.md that matches the files on disk, and every problem found.
function buildIndex() {
  const { foods } = JSON.parse(fs.readFileSync(path.join(ROOT, 'foods.json'), 'utf8'));
  const { recipes, errors } = loadRecipes(path.join(ROOT, 'recipes'), foods);
  const used = new Map([...recipes.keys()].map((k) => [k, new Map()]));
  const plansDir = path.join(ROOT, 'plans');
  for (const file of fs.readdirSync(plansDir).filter((f) => f.endsWith('.json')).sort()) {
    const slug = file.slice(0, -'.json'.length);
    const plan = JSON.parse(fs.readFileSync(path.join(plansDir, file), 'utf8'));
    (plan.days || []).forEach((day) => (day.meals || []).forEach((meal) => {
      const uses = used.get(meal && meal.recipe);
      if (uses) uses.set(slug, (uses.get(slug) || 0) + 1);
    }));
    resolvePlan(JSON.parse(JSON.stringify(plan)), recipes).errors.forEach((e) => errors.push(`plans/${file}, ${e}`));
  }

  const rows = [...recipes.entries()].filter(([, r]) => r).map(([key, r]) => {
    const t = r.ingredients.reduce((s, ing) => {
      const food = foods[ing.food];
      const k = (ing.grams || 0) / 100;
      return { kcal: s.kcal + food.kcal * k, p: s.p + food.p * k, c: s.c + food.c * k, f: s.f + food.f * k };
    }, { kcal: 0, p: 0, c: 0, f: 0 });
    const uses = [...used.get(key).entries()].map(([slug, n]) => `${slug} ×${n}`).join(', ');
    return { key, r, t, uses };
  });
  const cell = (s) => String(s).replace(/\|/g, '\\|');
  const r0 = Math.round;
  const lines = [
    '<!-- Generated by catalogue.js from recipes/*.json and plans/*.json. Do not edit: run `node catalogue.js`. -->',
    '',
    '# Recipes',
    '',
    `${rows.length} Recipes. Numbers are for \`portion\` 1 at the reference size (an 80 kg man), from \`foods.json\`. "Used in" counts the meals in each plan that name the Recipe.`,
  ];
  for (const slot of ORDER.filter((s) => SLOTS.includes(s))) {
    const inSlot = rows.filter(({ r }) => r.slots.includes(slot)).sort((a, b) => a.r.name.localeCompare(b.r.name, 'sq') || (a.key < b.key ? -1 : 1));
    if (!inSlot.length) continue;
    lines.push('', `## ${TITLE[slot]}`, '', '| Key | Name | Min | kcal | P | C | F | Tags | Used in |', '| --- | --- | --: | --: | --: | --: | --: | --- | --- |');
    inSlot.forEach(({ key, r, t, uses }) => lines.push(
      `| \`${key}\` | ${cell(r.name)} | ${r.minutes} | ${r0(t.kcal)} | ${r0(t.p)} | ${r0(t.c)} | ${r0(t.f)} | ${(r.tags || []).join(', ')} | ${uses || '(none)'} |`,
    ));
  }
  const usedFoods = new Set(rows.flatMap(({ r }) => r.ingredients.map((i) => i.food)));
  const unused = Object.keys(foods).filter((k) => !usedFoods.has(k));
  lines.push('', '## Foods no Recipe uses', '');
  if (unused.length) unused.forEach((k) => lines.push(`- \`${k}\` (${foods[k].sq})`));
  else lines.push('None.');
  return { text: `${lines.join('\n')}\n`, errors };
}

// True when recipes/INDEX.md matches the files on disk.
function indexIsCurrent() {
  const { text } = buildIndex();
  return fs.existsSync(INDEX) && fs.readFileSync(INDEX, 'utf8').replace(/\r\n/g, '\n') === text;
}

if (require.main === module) {
  const { text, errors } = buildIndex();
  errors.forEach((e) => console.log(`ERROR ${e}`));
  if (errors.length) process.exit(1);
  if (process.argv.includes('--check')) {
    if (!indexIsCurrent()) {
      console.log('recipes/INDEX.md is out of date: run node catalogue.js');
      process.exit(1);
    }
    console.log('recipes/INDEX.md is up to date.');
  } else {
    fs.writeFileSync(INDEX, text);
    console.log(`Wrote recipes/INDEX.md (${text.split('\n').filter((l) => l.startsWith('| `')).length} rows).`);
  }
}

module.exports = { buildIndex, indexIsCurrent };
